run_name = "Sens_truck_cost_multiplier_2"
qk = [ 100, 60, 40, 20,]
h_b = [ 4000, 2700, 2000, 1200,]
seed = 0
reduced = true
h_t_40 = 400
h_t_20 = 280
handling_time = 0.16666666666666666
C_range = [ 150, 175,]
N_range = [ 20, 20,]
Oc_range = [ 0, 24,]
Oc_offset_range = [ 50, 70,]
travel_time_long_range = [ 9, 13,]
travel_angle = 0.39269908169872414
P40_range = [ 0.2, 0.22,]
PExport_range = [ 0.05, 0.75,]
C_range_reduced = [ 100, 100,]
N_range_reduced = [ 8, 8,]
gamma = 100
big_m = 1000
