run_name = "Sens_handling_time_1"
qk = [ 40, 30, 15,]
h_b = [ 1600, 1500, 900,]
seed = 0
reduced = true
h_t_40 = 200
h_t_20 = 140
handling_time = 1
C_range = [ 150, 175,]
N_range = [ 20, 20,]
Oc_range = [ 0, 24,]
Oc_offset_range = [ 20, 70,]
travel_time_long_range = [ 9, 13,]
travel_angle = 0.39269908169872414
P40_range = [ 0.2, 0.22,]
PExport_range = [ 0.05, 0.75,]
C_range_reduced = [ 120, 120,]
N_range_reduced = [ 6, 6,]
gamma = 100
big_m = 1000
